run:
  concurrency: 4
  timeout: 10m

linters:
  enable:
    - revive
    - ginkgolinter
    - ineffassign
    - misspell
    - goimports
    - importas
    - unused

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: if-return
        disabled: true

issues:
  exclude: # Exclude stutter issues (for now)
    - "exported: type name will be used as (.+) by other packages, and that stutters; consider calling this (.+)"
